### PR TITLE
update comment block in Module.php as no Module::getAutoloaderConfig()

### PR DESCRIPTION
**Pull request by samsonasik**
means it must be using composer

### CODE REVIEW

**Comment by acelaya** [comment]
I would directly delete this file. What do you think?

**Comment by samsonasik** [comment]
placing Module.php file in zf2 root module is the "nature" structure imo, so i personally not remove this file.

Warm regards,

Abdul Malik Ikhsan

Pada 27 Feb 2015, pukul 23.30, Alejandro Celaya <notifications@github.com> menulis:

**Comment by acelaya** [comment]
You are probably right

**Comment by samsonasik** [comment]
Actually, after I re-think about it, the comment block itself need to be updated to make it work without composer with Zend\Loader ?

Warm regards,

Abdul Malik Ikhsan

Pada 28 Feb 2015, pukul 06.29, Alejandro Celaya <notifications@github.com> menulis:

**Pull request merged**
