### PR TITLE
update autoloader : already handled by composer on psr-4 autoload

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by acelaya** [comment]
Looks good. 
I use to add the autoloading files for those that don't use composer, but nowadays everybody uses composer. 
Also, I see I left the classmap file empty, so they are not going to be of any help anyway.

**Comment by samsonasik** [comment]
travis build seems failure, the Module::getAutoloaderConfig() seems need to return array(), I will update in some hours from now. I'm in mobile...

**Comment by acelaya** [comment]
No problem, I'll wait. I'm in mobile too.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
I've removed <code>ModuleTest::testGetAutoloaderConfig()</code> test as <code>Module::getAutoloaderConfig()</code> was removed. Travis should be green now ;)

**Comment by acelaya** [comment]
Thanks @samsonasik!
I'll probably end doing this in all my published modules. I think everybody should use composer to install and manage ZF2 modules.

**Comment by samsonasik** [comment]
:+1:

**Pull request merged**
